### ISSUE TITLE
Reset state with snapshots

### ISSUE THREAD

**Issue by yfei-z** [jgroups-extras/jgroups-raft#301] opened 2024-08-21 09:51 UTC
The snapshot could came from remote leader, when required logs no longer exist in leader, because a snapshot has been taken, in that case, the state machine should be fully rebuild since there may be removed state that can't be represented by the snapshot.
I think `ReplicatedStateMachine` and `CounterService` are not handling it properly.

**Comment by jabolina** [comment] 2024-08-21 13:17
Hmm, looking at the code for `Follower` it assumes the state machine rebuilds on the snapshot. I agree that the `ReplicatedStateMachine` and `CounterService` are affected.

A simple example with the `ReplicatedStateMachine` is an entry that is removed and committed by a majority (still not seen by all nodes), the leader sends the snapshot at the beginning of `sendAppendEntriesMessage` and truncates the log, one of the nodes which haven't seen the original remove operation receives the snapshot, the `ReplicatedStateMachine` only does a `putAll` operation with the data from the snapshot. This follower diverged from the rest of the cluster.

Are you interested in contributing with a PR to this one? Don't worry if it is not possible, reporting the issue is already a lot of help. I believe just doing a `Map#clear()` within the synchronized block on both `ReplicatedStateMachine` and `CounterService` would do the trick.

**Comment by yfei-z** [comment] 2024-08-22 03:45
Happy to do that. Actually I'm working on a LockService, I will make a PR if it's good enough.

**Closed** 2024-08-22 11:31 UTC
Labels: bug
